from telegram import Bot
from telegram.ext import Updater, CommandHandler
import schedule
import time

TOKEN = '8025928171:AAEH0pAVlD4Yh66nyx6un08ehUrVL2IHz9o'
CHAT_ID = '-4596272485'

def send_message(context):
    context.bot.send_message(chat_id=CHAT_ID, text="This is a scheduled message!")

def main():
    updater = Updater(TOKEN, use_context=True)
    job_queue = updater.job_queue
    job_queue.run_daily(send_message, time=time(hour=12, minute=36))  # Schedule for 9:00 AM daily

    updater.start_polling()
    updater.idle()

if __name__ == '__main__':
    main()
